import React, { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/provider/ApolloWrapper';
import { Toaster } from 'sonner';




export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = async ({ children }: PropsWithChildren) => {
 

  return (
    <html lang="en">
      <body className="bg-white">
        <ApolloWrapper>
          
          {children}
          <Toaster />
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
